
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-project
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./Notebook:/Notebook
      - ./src:/src
      - ./data:/data
      - ./logs:/logs
      - ./src:/src
    command: start-notebook.sh
